Repository Kamehamehaaaaa/UF-NestMate, pull requests merged in 2025-02, with the labels that each got.

#12 Frontend for the UF NestMate website
  .DS_Store
  .gitignore
  README.md
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/logo.png
  client/src/App.css
  client/src/App.js
  client/src/components/ContactForm/contactform.css
  client/src/components/ContactForm/contactform.js
  client/src/components/Header/Login/Login.js
  client/src/components/Header/Login/login.css
  client/src/components/Header/header.css
  client/src/components/Header/header.js
  client/src/components/SearchResults/searchresults.css
  client/src/components/SearchResults/searchresults.js
  client/src/images/HomePageBack.png
  client/src/images/blvd.png
  client/src/images/centric.png
  client/src/images/gainesvilleplace.png
  client/src/images/hideaway.png
  client/src/images/stoneridge.png
  client/src/images/sweetwater.png
  client/src/index.js
Labels: frontend

#14 Delete .DS_Store
  .DS_Store
Labels: bug

#25 Creating Sprint1.md
  Sprint1.md
Labels: documentation

#32 Made the apartment cards generate a pop-up window
  client/src/components/Header/Login/login.css
  client/src/components/SearchResults/searchresults.css
  client/src/components/SearchResults/searchresults.js
Labels: enhancement, frontend
