Repository Kamehamehaaaaa/UF-NestMate, pull requests merged in 2025-03, with the labels that each got.

#35 updating apis input to json from form data
  apis/housing/housing.go
  apis/main/main.go
  apis/router/housingHandler.go
  apis/router/routes.go
  apis/router/userHandler.go
  apis/user/user.go
Labels: bug, backend

#62 Comment Section changes
  apis/database.go
  apis/main.go
  client/src/components/Header/Login/Login.js
  client/src/components/Header/Login/login.css
  client/src/components/Header/header.js
  client/src/components/ProfilePage/ProfilePage.css
  client/src/components/ProfilePage/ProfilePage.js
  client/src/components/SearchResults/searchresults.css
  client/src/components/SearchResults/searchresults.js
Labels: frontend

#63 Improved contact form UI and error handling logic
  client/src/components/ContactForm/contactform.css
  client/src/components/ContactForm/contactform.js
Labels: enhancement, frontend

#64 Sprint3 e2e searchresult
  client/src/App.js
  client/src/components/ContactForm/contactform.css
  client/src/components/Header/Login/Login.js
  client/src/components/Header/header.css
  client/src/components/Header/header.js
  client/src/components/ProfilePage/ProfilePage.js
  client/src/components/SearchResults/searchresults.js
  package-lock.json
  package.json
Labels: enhancement, frontend

#68 Sprint3 handler rating
  apis/database.go
  apis/main.go
Labels: backend

#70 added ui changes for integrating filter apis
  client/src/App.js
Labels: frontend

#74 Server /setup for migration to swagger ui
  apis/docs/docs.go
  apis/docs/swagger.json
  apis/docs/swagger.yaml
  apis/go.mod
  apis/go.sum
  apis/main.go
Labels: enhancement

#81 housing tests
  apis/cloudinary/cloudinary.go
  apis/data/data.go
  apis/database/database.go
  apis/go.mod
  apis/go.sum
  apis/main.go
  apis/router/housingHandler.go
  apis/router/housingHandler_test.go
  apis/router/routes.go
  apis/router/test.jpg
Labels: backend

#83 user test cases
  apis/database/database.go
  apis/router/housingHandler.go
  apis/router/routes.go
  apis/router/userHandler.go
  apis/router/userHandler_test.go
Labels: backend
