Repository Kamehamehaaaaa/UF-NestMate, pull requests merged in 2025-04, with the labels that each got.

#87 Sprint3 unit test
  Sprint3.md
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/components/ContactForm/contactform.test.js
  client/src/components/Header/Login/login.test.js
  client/src/components/ProfilePage/ProfilePage.test.js
  client/src/components/SearchResults/searchresults.test.js
  client/src/setupTests.js
Labels: documentation, frontend

#93 Sprint4 work
  apis/database/database.go
  apis/housing/housing.go
  apis/router/housingHandler.go
  apis/router/routes.go
  apis/router/userHandler.go
  apis/router/userHandler_test.go
  apis/user/user.go
  client/client/.gitignore
  client/client/cypress.config.js
  client/client/cypress/e2e/searchresults.cy.js
  client/client/cypress/fixtures/example.json
  client/client/cypress/screenshots/searchresults.cy.js/Apartment Search Results -- Clicks the Search Apartment button (failed).png
  client/client/cypress/support/commands.js
  client/client/cypress/support/e2e.js
  client/cypress.config.js
  client/cypress/e2e/app.cy.js
  client/cypress/e2e/contactform.cy.js
  client/cypress/e2e/login.cy.js
  client/cypress/e2e/match.cy.js
  client/cypress/e2e/profilesection.cy.js
  client/cypress/e2e/searchresults.cy.js
  client/src/App.js
  client/src/components/Header/Login/Login.js
  client/src/components/Header/Login/login.css
  client/src/components/Header/header.js
  client/src/components/Matches/matches.css
  client/src/components/Matches/matches.js
  client/src/components/Matches/matches.test.js
  client/src/components/ProfilePage/ProfilePage.css
  client/src/components/ProfilePage/ProfilePage.js
  client/src/components/RoommatePreferencesForm/RoommatePreferencesForm.css
  client/src/components/RoommatePreferencesForm/RoommatePreferencesForm.js
  client/src/components/RoommatePreferencesForm/RoommatePreferencesForm.test.js
  client/src/components/SearchResults/searchresults.css
  client/src/components/SearchResults/searchresults.js
  client/src/hooks/useAmenities.js
  client/src/index.js
Labels: bug, enhancement, backend, frontend

#92 enhancement on the summarizer
  apis/docs/swagger.yaml
  apis/router/commentsHandler.go
  apis/router/commentsHandler_test.go
  apis/router/housingHandler.go
  apis/router/routes.go
Labels: backend

#97 Updated Swagger with latest apis
  apis/docs/swagger.yaml
Labels: backend

#98 Update README.md
  README.md
Labels: documentation

#99 unit tests for favorites handler
  apis/router/housingHandler.go
  apis/router/routes.go
  apis/router/userHandler_test.go
  apis/user/user.go
Labels: backend

#101 Created Sprint4.md and added instructions to run our app in first-page README.md
  README.md
  Sprint4.md
Labels: documentation

#104 preferences apis tests
  apis/router/housingHandler_test.go
  apis/router/userHandler_test.go
  apis/user/user.go
Labels: backend

#107 Updated directions to run the app locally
  README.md
Labels: documentation

#108 added missing summarizer files
  apis/housing/summarizer.go
Labels: backend
